### ISSUE TITLE
Inverse dynamics in `mjx`

### ISSUE THREAD

**Issue by alberthli** [google-deepmind/mujoco#1211]
In the `mjx` [feature matrix](https://mujoco.readthedocs.io/en/stable/mjx.html#feature-parity), I see that inverse dynamics are unimplemented - is there an estimate for when this will be ready at the same level as `mjx.forward`? This would be very useful for trajectory-optimization-based applications.

**Comment by erez-tom** [comment]
We don't know yet when we'll implement it, because we haven't yet explored enough how it may be used; so we'd love to hear more about your intended use!

We recently implemented [direct trajectory optimization](https://github.com/google-deepmind/mujoco_mpc/tree/main/mjpc/direct) using inverse dynamics in C++ (so on CPU), and we currently solve the optimization problem by [Banded Cholesky Factorization](https://github.com/google-deepmind/mujoco/blob/cd56a41f835bc4c43ccf00d0b18bdea20411aa42/src/engine/engine_util_solve.h#L56), an algorithm that (we expect) would not run efficiently on accelerators. [Trajax](https://github.com/google/trajax) also runs mostly on CPU, even though it's written in JAX.

What do you have in mind for inverse-dynamics MJX?  Can you suggest a trajectory optimization algorithm that uses inverse dynamics and is amenable to fast computation on an accelerator?  If not, why would you want use inverse dynamics in MJX instead of simply using MuJoCo-C's existing implementation?

If any of this seems interesting / relevant to your research, please get in touch with us at mujoco@deepmind.com .

Best of luck!
