### ISSUE TITLE
Different conventions for contact.pos values in MJX?

### ISSUE THREAD

**Issue by kli58** [google-deepmind/mujoco#1325]
Hi,

I'm a student trying to use MJX for a bipedal robotics project I am working on where I need ground reaction force information and their locations. Since there's no sensor feature yet, I am trying to get this information from mjx_data.contact. It looks like the contact position mjx return is different from the standard mujoco? 

Here is a minimum example which explains my question:

```
import jax, mujoco
from mujoco import mjx

XML=r"""
<mujoco>
    <worldbody>
        <geom conaffinity="3" condim="3" friction="1 .1 .1" name="plane"
            rgba=".9 .9 .9 1"
            size="10 5 0.1"
            type="plane"/>
        <body name="box" pos="0 0 0.1">
            <freejoint/>
            <geom type="box" size="0.1 0.1 0.1" density="500"/>
        </body>
    </worldbody>
</mujoco>
"""

model = mujoco.MjModel.from_xml_string(XML)
data = mujoco.MjData(model)
mujoco.mj_forward(model, data)

mjx_model = mjx.device_put(model)
mjx_data = mjx.device_put(data)

mujoco.mj_forward(model, data)
print("mujoco: \n", data.contact.pos)

mjx_data = mjx.forward(mjx_model, mjx_data)
print("mjx: \n", mjx_data.contact.pos)
```

The output for this script is 
```
mujoco: 
 [[-0.1 -0.1  0. ]
 [ 0.1 -0.1  0. ]
 [-0.1  0.1  0. ]
 [ 0.1  0.1  0. ]]
mjx: 
 [[-0.1 -0.1  0. ]
 [ 0.1  0.1  0.2]
 [-0.1  0.1  0. ]
 [-0.1 -0.1  0. ]]
```

**Comment by btaba** [comment]
Hi @kli58 

Yes the contact model for convex objects (e.g. box) is different between MuJoCo and MJX.  I thought this was clearly stated in the docs, but it's not stated clearly. We'll add more info to the docs.

In your example above, the box is not penetrating the plane (check `mjx_data.contact.dist`). For non-penetrating contact dists, the position of the contact is garbage (since there's no contact!), but it will still be present in MJX (due to jax shenanigans). Check out the python [viewer](https://github.com/google-deepmind/mujoco/blob/main/mjx/mujoco/mjx/viewer.py) in MJX with your box example to get a feel for how contacts work (hit 'c' and 'f' to see the contacts).
