### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by rishabkr29** [google-deepmind/mujoco#1348]
Hi,

I'm a student and I'm trying to use MuJoCo for thesis work. Initially I was using cable model  #1336 for modelling my system but because of cable slacking and equality constraint, I planned to model tendon as cable and trying to actuate it with the position and velocity servo.  I wanted to perform position control.

I have few quires which I am expecting from the contributor to answer it.
1. 
I'm looking for some help related to my simulation which is not working according to need, I am calculating the reference slider displacements (s1,s2,s3 & s4 ) for all the cables (actually tendon using stiffness as 100000 and damping as 0.01) and setting the gain and bias parameters (kp = 170  and kv = 30 for all actuators) i.e. for the 4 position and 4 velocity actuators. 

I am assigning data.ctrl [0] = s1   # position actuator 
                        data.ctrl [1] = s2 , #  position actuator 
                        data.ctrl [2] = s3 ,  # position  actuator 
                        data.ctrl [3] = s4    # position actuator 

2. 
After reading about the position and velocity actuator a lot,  I don't have a clear idea how these two are working with the Equation of Motion ? at the same time I do understand the control input ui are being mapped to scalar force Pi based on the  gain and bias parameters. 
also  #1337  how to tuned the kp and kv  values theoretically (using governing equation)?

3.
Also, I feel there is flaw in modelling the tendon as a cable, I feel it is behaving like a rod which it should not be?

Thanks in Advanced ! 

Here is a video of Tendon Model, illustrating my question 1 and 3. 

https://github.com/google-deepmind/mujoco/assets/110694658/79b0b3e8-ba5b-484d-bbdf-863952cd9391

**Comment by Balint-H** [comment]
If the actuators are set up as position actuators for tendons, then setting their `ctrl` will set the equilibrium length of that tendon. Similarly, velocity actuators will apply forces that bring the tendon length's rate of change towards the value provided in `ctrl`. Setting values in `data.ctrl` will not change any of the gain or bias parameters of the actuators, only the target of the actuator. If by tendon's behaving as rods you mean they are under compression instead of only tension, you have to set the lower range of the tendon length to be 0, so that it is permitted to shorten.
