### ISSUE TITLE
[MJX] visualize parallel environments in one viewer 

### ISSUE THREAD

**Issue by panwliu** [google-deepmind/mujoco#1356]
First of all, thanks for the great work! MJX could make a great impact in the robotics community.

I'm doing massive parallel simulation using MJX. During the development phase, I'd like to visualize the parallel environments. For example, I spawned 4096 humanoids, and I'd like to visualize them all in a viewer as the image (a screenshot of Isaac Gym). I saw that [mjx/mujoco/mjx/viewer.py](https://github.com/google-deepmind/mujoco/blob/main/mjx/mujoco/mjx/viewer.py) is used to visualize one environment. How to visualize the parallel environments in one viewer?

Thanks
![Screenshot from 2024-01-21 14-57-55](https://github.com/google-deepmind/mujoco/assets/52264766/886da6a7-f4cc-40e2-96c8-36b6cf9cfb28)

**Comment by rs545837** [comment]
Yes I am also very curious to know if there's a way to do it @yuvaltassa.

**Comment by btaba** [comment]
Hi folks,

For the MJX part, you can simulate N environments and write them back to MjData via [`get_data`](https://github.com/google-deepmind/mujoco/blob/3b0a680fa7acf69a3cc3fc72f91402bfeb50490d/mjx/mujoco/mjx/_src/io.py#L232) which accepts a batched `mjx.Data`.

Now for visualizing N environments, the simplest way I can think of is to create an `MjModel`/`MjData` with N characters (procedurally generate the XML or use something like `dm_env` composer), and then feed the qpos from the above step back into your `MjData`.  Others should comment on this replication bit though. I know that there has been some active discussion on better ways to `repeat` bodies.

**Comment by panwliu** [comment]
Hi @btaba , thanks for the response.

Since mujoco doesn't allow repeated bodies in the XML, it actually makes procedurally generating N characters not trivial. Also needs careful handling in feeding the batched `mjx.Data`  to the right bodies.

Another possible way would be a "batched" version of `mjModel`. Would you think this as an option?

**Comment by yuvaltassa** [comment]
I think what you want is visual only, no? Like, your humanoids don't need to touch each other at all, right?

This is something that @vikashplus (and, as it turns out, #1395) have asked for.

What you actually want, IIUC, is something like [mjv_updateScene](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mjv-updatescene), except you want "`mjv_addToScene`", i.e. some way to add together the geoms from multiple `mjData` instances into one visual scene. Correct?

**Comment by vikashplus** [comment]
+1 `mjv_addToScene` will be amazing. I have been trying to hack this in multiple ways.

**Comment by panwliu** [comment]
> some way to add together the geoms from multiple mjData instances into one visual scene

@yuvaltassa, exactly!

**Comment by yuvaltassa** [comment]
Okay, this is MUCH easier than your initial proposal. I'll try to do something like this in the next few days, will update here.

**Comment by AlexS28** [comment]
@yuvaltassa was wondering if there was any update on this feature. I think it would be really great to have, and not only good to get a nice overview for how the robots are behaving, but also nice for making videos for research papers etc.

**Comment by alexhansson** [comment]
@yuvaltassa Any update on this? Would definitely be huge if this is somehow possible!

**Comment by yuvaltassa** [comment]
So this turned out to be rather easy. All you need is the API function [mjv_addGeoms](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mjv-addgeoms) which, as the name suggests, adds geoms to an existing scene. I added a section to the [tutorial colab](https://github.com/google-deepmind/mujoco?tab=readme-ov-file#getting-started) showing how to do this.
