### ISSUE TITLE
Modeling static friction/stiction

### ISSUE THREAD

**Issue by kylestach** [google-deepmind/mujoco#1366]
I'm trying to use MuJoCo to model a robot with as many "nasty" real-world effects as possible. I'm not trying to make it match a particular robot, but I'd like to be able to model joint and contact stiction (where the coefficient of friction is reduced when the contact has nonzero velocity).

_(obligatory: yes, I know this model of friction is ill-defined, e.g. Painleve problems, but these effects are pretty standard so I'm somewhat surprised there isn't a standard workaround)_

With joints it seems like the easiest workaround is to just have a hook (doesn't look like there's a plugin architecture supporting this, but it can be done in a sim script) to modify the `frictionloss` parameter based on whether the joint velocity is nonzero.

For contacts it seems like it might be harder to hack around because it's not clear that there's a concept of "contact velocity" for a contact pair (https://github.com/google-deepmind/mujoco/blob/main/include/mujoco/mjdata.h#L98-L129). Here's what I'm currently thinking:
1. After contact resolution: compute global velocity (twist?) of contacting bodies evaluated at the point of contact
2. Take tangential components of velocity only and compute magnitude
3. Set friction coefficients to stiction values if tangential velocity is small, or dynamic values otherwise (or use Stribeck friction model, etc).
I'm not super familiar with MuJoCo internals - how does the contact position get chosen for 1D (edge) or 2D (planar) contacts when infinitely many points from the two bodies are in contact? It seems like the above will be wrong for rotating bodies with these types of contact, but that may be "good enough" depending on how the representative point is chosen?

Related issue about state-dependent friction contacts: https://github.com/google-deepmind/mujoco/issues/717

(As a side note: I'm also also interested in modeling motor temperature and backlash but those seem more straightforward to implement with an actuator plugin and extra hinge joints, respectively. That said, if you have any pointers I'd appreciate it.)

**Comment by yuvaltassa** [comment]
Hi @kylestach, thanks for the detailed and precisely worded issue. Bottom line is that you are thinking about everything correctly and are in the right direction, I just have a few pointers that I think will be helpful.

First, use elliptic cones. They are much more realistic than pyramidal (with the possible exception of contacts between certain rombohedral and triclinic crystals smoothly cut along just the right axis, go read the old Anitescu papers if you really want to know) but more importantly, their Jacobians are what you want/expect from a contact Jacobian: `{normal, tangent, tangent}`. 

This is important because the statement
>  it's not clear that there's a concept of "contact velocity" for a contact pair

is (obviously?) not true. How could MuJoCo compute friction force without it being easy and cheap to compute contact velocity? The correct statement is that computing contact velocity is _not well documented_ 🙂 

Say that you've found your contact(s) `i` in the `mjData.contact` array. If defined using `<pair>` this is simply the set of contacts whose `contact[i].geom[0,1]` ids correspond to the geom pair in question. An [mjContact](https://mujoco.readthedocs.io/en/latest/APIreference/APItypes.html#mjcontact) has an int attribute `efc_address` which tells you the first row in the constraint Jacobian corresponding to the contact. Assuming we are using elliptic cones, `efc_address + {1, 2}` are the tangent directions. Instead of now messing about with the sparse matrix representation, you have the convenience function [`mj_mulJacVec`](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-muljacvec), which gives you what you need: 

- Doing `mj_mulJacVec` with `res = mjData.qvel` will give you an `nefc`-length vector `res` containing all constraint velocities and `res[efc_address + {0, 1, 2}]` will contain the velocities in the `{normal, tangent, tangent}` directions for your contact, respectively. 

Regarding this question
> how does the contact position get chosen for 1D (edge) or 2D (planar) contacts when infinitely many points from the two bodies are in contact?

That depends on the type of geoms colliding but TL;DR it picks some sensible set of point contacts. The box-box collider for example can generate up to 8 (at the intersection points of a [simple regular octagram](https://en.wikipedia.org/wiki/Octagram#Star_polygon_compounds)). Generally (e.g. for meshes) you get only one contact point using libCCD's [Minkowski Portal Refinement](https://en.wikipedia.org/wiki/Minkowski_Portal_Refinement), but you can get (up to 4) more if you turn on the [multiccd](https://mujoco.readthedocs.io/en/latest/XMLreference.html#option-flag-multiccd) flag.

Hope this helps! 

Closing for now but feel feel to continue the conversation here.
