### ISSUE TITLE
Engine error if mjcb_passive callback installed before model instantiation

### ISSUE THREAD

**Issue by tmplt** [google-deepmind/mujoco#1376]
On x86 Linux with mujoco 3.1.1, in a REPL, a passive force callback can be installed after model instantiation without issue:
```python
>>> import mujoco
>>> def callback(model, data):
...     print("callback")
...
>>> model = mujoco.MjModel.from_xml_string('<mujoco/>')
>>> data = mujoco.MjData(model)
>>> mujoco.set_mjcb_passive(callback)
>>> mujoco.mj_step(model, data)
callback
```

But not before:
```python
>>> import mujoco
>>> def callback(model, data):
...     print("callback")
... 
>>> mujoco.set_mjcb_passive(callback)
>>> model = mujoco.MjModel.from_xml_string('<mujoco/>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Error: engine error: Python exception raised
```

**Comment by nimrod-gileadi** [comment]
This is probably because during mjModel construction we run an mj_step using an internal temporary mjData.

The callback implementation in [callbacks.cc](https://github.com/google-deepmind/mujoco/blob/3.1.2/python/mujoco/callbacks.cc#L174) tries to find the Python objects corresponding to mjModel and mjData, and fails because that mjData wasn't created through Python, and MjModel is not finished construction.

I think our options are:
1. Try to create temporary py::objects for the mjModel and mjData in this situation, to call the callback.
2. Disable all callbacks during this internal run of mj_step.
