### ISSUE TITLE
About Compiler with *.obj files

### ISSUE THREAD

**Issue by XinchenYin** [google-deepmind/mujoco#1529]
**How to ask for help**

Hi,

I'm a student and I'm trying to use MuJoCo for rendering articulated objects.

I'm looking for some help with compile from urdf files to xml files.

When I'm trying to convert urdf files downloaded from SAPIEN, I found they are using obj files for meshes. Seems they are not supported by built-in compiler of mujoco. How should I deal with that

Here is a screenshot / video, illustrating my question:
![image](https://github.com/google-deepmind/mujoco/assets/126395215/f9a15f2e-d434-4285-a81f-cefba5e65f21)
![image](https://github.com/google-deepmind/mujoco/assets/126395215/3ff97c36-c91c-4a46-963d-9ec67a426bae)

**Comment by yuvaltassa** [comment]
The compiler is telling you what the problem is: "faces have inconsistent orientation", i.e. the mesh is malformed. This is required by the [exactmeshinertia](https://mujoco.readthedocs.io/en/latest/XMLreference.html#compiler-exactmeshinertia) computation. However, since this option is off by default, there is no reason to required that the mesh be well-formed in all cases. After I926c385475dd79f07e88fe1925ecbb2adb4f8917 this is no longer required.
