### ISSUE TITLE
MuJoCo cup model penetrating floor/table

### ISSUE THREAD

**Issue by cherylwang20** [google-deepmind/mujoco#1701]
Hi,

I'm a student and I'm trying to use MuJoCo to simulate grabbing a concave object (e.g. beaker) with a UR10e Robotic Arm. I am trying to start with the cup model as a reference but it looks like the cup is penetrating the floor when positioned sideways. 

![screenshot](https://github.com/google-deepmind/mujoco/assets/90352960/87ceecfe-6680-4b8e-bdcc-e2aed0e72a51)

I tried putting it in the robohive env and it is also penetrating the table that I am positioning on. 

![screenshot](https://github.com/google-deepmind/mujoco/assets/90352960/0b842f78-aab6-4995-aaef-448d1d4df7b7)

I'm looking for some help with potentially how to modify the collision type on the side so that it behaves correctly. I see that in this demo: https://github.com/google-deepmind/mujoco/discussions/357#discussioncomment-3022028, the cup is colliding well with the floor. 

Here is the link to the XML file that I am using:
[
robohive/envs/arms/ur10e/scene_gripper.xml](https://github.com/cherylwang20/mj_envs/blob/76784b850b37901cae7c9c2f6c94a47b1e129809/robohive/envs/arms/ur10e/scene_gripper.xml)

Any help is appreciated! Thank you.

**Comment by cherylwang20** [comment]
I tried again and it looks like when the cup is positioned in the upright position and then letting the cup fall, it is not penetrating, it's only when the cup initially starts with a side-way position that this penetration is happening. 

![screenshot](https://github.com/google-deepmind/mujoco/assets/90352960/99224844-4928-4525-ac3c-9734731980b2)

Is there any possible explanation for this behavior?

**Comment by Balint-H** [comment]
How do you set the rotation of the mug? Do you just apply pure rotation to the freejoint? 

Since the body frame of the mug starts at the bottom, rotation without position offset will cause it to penetrate the surface. Depending on the thickness of the surface, this can cause the mug to get stuck. You can either increase the thickness of the surface, disable the table collisions and add a plane instead, or offset the mug to prevent the penetration. 

If you need it on its side, you just need to move it upwards with a height equal to the mug's radius.

**Comment by kevinzakka** [comment]
I think this has been addressed in https://github.com/kevinzakka/obj2mjcf/issues/31. @cherylwang20 Feel free to re-open if you run into further issues.
