### ISSUE TITLE
Gravity: Blocks not falling

### ISSUE THREAD

**Issue by omarrayyann** [google-deepmind/mujoco#1727]
For some reason the blocks I add are not falling due to gravity. This is my xml:

<?xml version="1.0" ?>
<mujoco model="iiwa14_scene">
    
    <include file="iiwa14.xml"/>
    <include file="table.xml"/>

    
    <statistic center="0.2 0 0.2" extent="1.0"/>
    <option timestep="0.001" gravity="0 0 -9.81"/>

    <visual>
        <headlight diffuse="0.6 0.6 0.6" ambient="0.3 0.3 0.3" specular="0 0 0"/>
        <rgba haze="0.15 0.25 0.35 1"/>
        <global azimuth="-120" elevation="-20"/>
    </visual>

    <asset>
        <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>
        <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
          markrgb="0.8 0.8 0.8" width="300" height="300"/>
        <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>
    </asset>

    <worldbody>
        <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
        <geom name="floor" size="5 5 0.05" type="plane" material="groundplane"/>
        <body name="cylinder" pos="0 0 0.2">
            <geom name="cylinder_geom" type="cylinder" size="0.14 0.2" rgba="0.1 0.1 0.1 1"/>
        </body>
        
        <body name="red_block" pos="0.65 0 0.5" euler="0 0 0">
            <geom name="red_block_geom" type="sphere" size="0.025 0.025 0.025" rgba="1 0 0 1" mass="0.1"/>
        </body>
    </worldbody>
</mujoco>

**Comment by yuvaltassa** [comment]
See [documentation](https://mujoco.readthedocs.io/en/latest/overview.html#joint):

"Joints are defined within bodies. _**They create motion degrees of freedom (DOFs) between the body and its parent. In the absence of joints the body is welded to its parent.**_ This is the opposite of gaming engines which use over-complete Cartesian coordinates, where joints remove DOFs instead of adding them. There are four types of joints: ball, slide, hinge, and a _**“free joint” which creates floating bodies**_. A single body can have multiple joints. In this way composite joints are created automatically, without having to define dummy bodies. The orientation components of ball and free joints are represented as unit quaternions, and all computations in MuJoCo respect the properties of quaternions."

This is also covered in the [introductory tutorial](https://github.com/google-deepmind/mujoco?tab=readme-ov-file#getting-started).

**Comment by omarrayyann** [comment]
Thanks!
