### ISSUE TITLE
Can users change the mjNGROUP which is constant to facilitate mj_ray method？

### ISSUE THREAD

**Issue by friedmainfunction** [google-deepmind/mujoco#706]
Hi,

I'm a (student) and I'm trying to use MuJoCo for physical simulation.

I'm looking for some help with the mechanism of mjNGROUP.

I noticed that mjNGROUP is a constant value that is defined in mjvisualize.h, but mj_ray relies on this setting, which means: at most, I can only detect six groups via mj_ray in one world. Is there any way to solve this except for changing the source code? Or is there some specific consideration? Any help is appreciated and thanks for this amazing software.

**Comment by yuvaltassa** [comment]
Your observation is correct. The reason for `mjNGROUP==6` is simply because groups are also used for visualisation, and the GUI needs `mjNGROUP` to create buttons. However, you can set the actual group value to whatever you like.

AFACT the only issue with `mj_ray` is the `mjMIN` in [this line](https://github.com/deepmind/mujoco/blob/cd99fbd59dc75fa8be97fe90a391d2055ee0a4d6/src/engine/engine_ray.c#L83). If you delete that `mjMIN` everything should work as expected, I think.

You're welcome to do this yourself and let us know if it works. If you like, you can submit a PR (but make sure to add a test to [engine_ray_test.cc](https://github.com/deepmind/mujoco/blob/main/test/engine/engine_ray_test.cc)).

**Comment by nimrod-gileadi** [comment]
Apologies if this is still an issue for you. Closing since there hasn't been any activity on this issue in a while.
